### PR TITLE
Sends View

### PR DESCRIPTION
**Pull request by mikk1max**
* feat: sends view, progress bar

* refactor: .gitignore file

### CODE REVIEW

**Comment by mikk1max** [comment]
This part of the code is not yet completed.

**Comment by mikk1max** [comment]
Sends View now is completed. Please make fast review! ;)

**Comment by mikk1max** [comment]
Made Firebase integration a little. For using, I will add you to Editors later and you will have fireBase.config file.

**Review by Boberman1 — APPROVED** [review]
God job!

**Pull request merged**
